# Generated by Django 4.2.27 on 2026-01-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_episode_error_message_alter_anime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='cover_image',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='source_url',
            field=models.URLField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='source_url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
