# Generated by Django 4.2.27 on 2026-01-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_alter_anime_cover_image_alter_anime_source_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['id']},
        ),
    ]
