# Generated by Django 4.2.27 on 2026-01-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_alter_episode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
